#Configuration file example, following TOML
c = 343	
#duration = 0.05 #in seconds, aiming for 4 reflections between the most distant walls
duration = 0.33 #in seconds, chosen using the rooms reverberation time
[mesh]
filename = "3x4x2,5_cartres_mesh" #.jld2 added by script
type = "Cartesian" #Types: "Tetraheder" "Cartesian"
	[mesh.dimensions]
	x = 3.0
	y = 4.0
	z = 2.5
	tll = 0.264 #Aiming for right above 10 Î”l at 120Hz
[surfaces]
#name = ["reflecting", "transmitting"] #This is currently not used by the script
r_factor = 0.25 #Just a randomly chosen value where sound energy will get reduced over time.
[sources] #just placed close to a corner.
x = [0.3]
y = [0.3]
z = [0.3]
amp = [1000] #Just really chosen a value, as long as it's above 0 the result is the same.
freq = [3430] #kHz
type = ["dirac"] #Types : "sine"	"dirac"
periods = [1]
[measurements]
filename = "cart_reverb/IR" #.jld2 added by script
	[measurements.microphones]
	x = [1.5, 0.3, 1.8] #trying to have it spread out somewhat without following a pattern.
	y = [2, 3.7, 1.2]
	z = [1.25, 0.3, 2]

