#Configuration file example, following TOML
c = 343
duration = 20 #in seconds
[mesh]
filename = "example_sphere" #.jld2 added by script
type = "Tetraheder"
	[mesh.dimensions]
	r = 1 #using radius instead of XYZ makes the code detect it's sphere shape
	tll = 1.0
[surfaces] #This is currently not used by the script
name = ["reflecting", "transmitting"]
r_factor = [1, 0]
[sources]
x = [2,1,1]
y = [6,1,2]
z = [2,1,3]
amp = [2, 4, 1]
freq = [1, 1, 3] #kHz
type = ["sine", "dirac", "sine"]
[measurements]
filename = "example" #.jld2 added by script
	[measurements.microphones]
	x = [5, 10]
	y = [5, 10]
	z = [5, 10]
