#Configuration file example, following TOML
c = 343	
duration = 0.0045 #in seconds
[mesh]
filename = "1x1x1_20_tetra_mesh2" #.jld2 added by script
type = "Tetraheder" #Types: "Tetraheder" "Cartesian"
	[mesh.dimensions]
	x = 1.3
	y = 1.3
	z = 1.3
	tll = 0.005
[surfaces] #This is currently not used by the script
#name = ["reflecting", "transmitting"]
r_factor = 1
[sources]
x = [0.5]
y = [0.5]
z = [0.5]
amp = [10]
freq = [3430] #kHz
type = ["sine"] #Types : "sine"	"dirac"
periods = [1]
[measurements]
filename = "tet_propagation_20_retry" #.jld2 added by script
	[measurements.microphones]
	x = [0.57071, 0.71213, 0.92426, 0.58536, 0.75607, 1.0121, 0.6, 0.8, 1.1]
	y = [0.57071, 0.71213, 0.92426, 0.535355, 0.60607, 0.71213, 0.5, 0.5, 0.5]
	z = [0.5, 0.5, 0.5, 0.53827, 0.6148, 0.7296, 0.5, 0.5, 0.5]

	#From the source these are all in polar coordinates:
	#r: 0.1, 0.3 and 0.6; θ: 90°, 67.5°, 90° φ:45°, 22.5°, 0°
	#The source/microphones might be to close to the wall to avoid microphone reflections
