#Configuration file example, following TOML
c = 343	
duration = 0.0045 #in seconds
[mesh]
filename = "1.15x0.95x0.8_20_tetra_mesh" #.jld2 added by script
type = "Tetraheder" #Types: "Tetraheder" "Cartesian"
	[mesh.dimensions]
	x = 1.15 #0.25+0.8
	y = 0.95 #0.25+0.7
	z = 0.8 #0.25+0.55
	tll = 0.005
[surfaces] #This is currently not used by the script
name = ["reflecting", "transmitting"] #This is currently not used by the script
r_factor = 1
[sources]
x = [0.25]
y = [0.25]
z = [0.25]
amp = [10]
freq = [3430] #kHz
type = ["sine"] #Types : "sine"	"dirac"
periods = [3]
[measurements]
filename = "tet_propagation_20" #.jld2 added by script
	[measurements.microphones]
	x = [0.32071, 0.46213, 0.67426, 0.33536, 0.50607, 0.76214, 0.35, 0.55, 0.85]
	y = [0.32071, 0.46213, 0.67426, 0.285355, 0.35607, 0.46214, 0.25, 0.25, 0.25]
	z = [0.25, 0.25, 0.25, 0.28827, 0.3648, 0.47962, 0.25, 0.25, 0.25]
	#From the source these are all in polar coordinates:
	#r: 0.1, 0.3 and 0.6; θ: 90°, 67.5°, 90° φ:45°, 22.5°, 0°
	#The source/microphones might be to close to the wall to avoid microphone reflections
