#Configuration file example, following TOML
c = 343	
duration = 0.003 #in seconds
[mesh]
filename = "1.15x0.95x0.95_20_cart_mesh" #.jld2 added by script
type = "Cartesian" #Types: "Tetraheder" "Cartesian"
	[mesh.dimensions]
	x = 1.15 #0.25+0.8
	y = 0.95 #0.25+0.7
	z = 0.95 #0.25+0.7
	tll = 0.005
[surfaces] #This is currently not used by the script
name = 1
r_factor = 1
[sources]
x = [0.25]
y = [0.25]
z = [0.25]
amp = [10]
freq = [3430] #kHz
type = ["sine"] #Types : "sine"	"dirac"
periods = [3]
[measurements]
filename = "cart_propagation_20" #.jld2 added by script
	[measurements.microphones]
	x = [0.35, 0.55, 0.85, 0.32071, 0.46213, 0.67426, 0.3, 0.4, 0.55]
	y = [0.25, 0.25, 0.25, 0.32071, 0.46213, 0.67426, 0.3, 0.4, 0.55]
	z = [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.32071, 0.46213, 0.67426]
	#From the source these are all in polar coordinates:
	#r: 0.1, 0.3 and 0.6; θ: 90, 90, 45 ; Φ: 0 , 45, 45

