#Configuration file example, following TOML
c = 343	
duration = 0.0025 #in seconds
[mesh]
filename = "0.3x0.3x0.3_20_cart_mesh" #.jld2 added by script
type = "Cartesian" #Types: "Tetraheder" "Cartesian"
	[mesh.dimensions]
	x = 0.3
	y = 0.3
	z = 0.3
	tll = 0.005
[surfaces] #This is currently not used by the script
#name = ["reflecting", "transmitting"]
r_factor = 0
[sources]
x = [0.1]
y = [0.1]
z = [0.1]
amp = [10]
freq = [3430] #kHz
type = ["sine"] #Types : "sine"	"dirac"
periods = [3]
[measurements]
filename = "cart_propagation_20 short" #.jld2 added by script
	[measurements.microphones]
	x = [0.15, 0.2, 0.13536, 0.17071, 0.125, 0.15, 0.1]
	y = [0.1, 0.1, 0.13536, 0.17071, 0.125, 0.15, 0.1]
	z = [0.1, 0.1, 0.1, 0.1, 0.13536, 0.17071, 0.1]
	#From the source these are all in polar coordinates:
	#r: 0.05, 0.1; θ: 90, 90, 45 ; Φ: 0 , 45, 45

